version: '3.5'
services:
  atlas: # NGINX
    build:
      args:
        - BUILD_ENV=acc
      context: .
    ipc: host

  test-unit-integration:
    build:
      context: .
      target: build-deps
    environment:
    - NODE_ENV=development
    command: npm run test

  test-e2e:
    build:
      dockerfile: Dockerfile
      context: ./test/e2e/
    links:
      - atlas:acc.data.amsterdam.nl
    environment:
      # Note that baseUrl must be formatted so
      # calls to API pass CORS check!
      - CYPRESS_baseUrl=http://acc.data.amsterdam.nl
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: npm run test-e2e

  test-e2e-aria:
    build:
      dockerfile: Dockerfile
      context: ./test/aria/
    links:
      - atlas:atlas
    environment:
      - BASE_URL=http://atlas:80
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: ./test-e2e-aria.sh

  test-health-checks:
    image: repo.data.amsterdam.nl/datapunt/atlas-health-checks:latest
    environment:
      - API_ROOT=https://acc.api.data.amsterdam.nl
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE_PLUS

